services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"           # Web UI
      - "1883:1883"           # MQTT
      - "7070:7070"           # Edge RPC
      - "5683-5688:5683-5688/udp"  # CoAP/LwM2M
    environment:
      TB_QUEUE_TYPE: in-memory
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard