services:
  mytb:
    restart: always
    image: "thingsboard/tb-postgres"
    ports:
      - "8080:8080"
      - "1883:1883"
      - "7070:7070"
      - "5683-5688:5683-5688/udp"
    environment:
      TB_QUEUE_TYPE: in-memory
      JAVA_OPTS: "-Dserver.address=0.0.0.0"
    volumes:
      - mytb-data:/data
      - mytb-logs:/var/log/thingsboard